
# Additional info: https://dcm.dev/docs/rules/
dart_code_metrics:
  rules-exclude:
    - test/**
    - lib/generated/**
    - integration_test/**

  extends:
    - recommended
  rules:
    - no-magic-string: false
    - format-comment: false
    
    